on join:
    wait 1 seconds
    send formatted "<link:https://github.com/nlaocs/pr_skript/>&nこちらのリポジトリ<reset>のmainブランチは、"
    send "このサーバーのskriptと同期されています。"
    send formatted "<link:https://github.com/nlaocs/pr_skript/>&nこのリポジトリ<reset>にプルリクエストを送ることで、"
    send "各自が自由に機能を追加することができます。"
    send "ゲーム性が壊れるコード(OP取得、クリエ取得等)以外ならマージします。"
    send "FLY等の機能追加は大歓迎です。"
    send "特定の個人のみが使える機能の追加はご遠慮ください。"
    send "公開直後なので、同期のシステムが不安定かもしれませんが、"
    send "ご了承ください。"
